<?php


/**
 * This class defines the structure of the 'Card' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Sep 30 06:33:12 2010
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class CardTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.CardTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('Card');
		$this->setPhpName('Card');
		$this->setClassname('Card');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('CARD_NUMBER', 'CardNumber', 'VARCHAR', true, 32, null);
		$this->addColumn('PIN_CODE', 'PinCode', 'VARCHAR', true, 16, null);
		$this->addColumn('IS_ACTIVE', 'IsActive', 'BOOLEAN', true, null, true);
		$this->addForeignKey('OWNER', 'Owner', 'INTEGER', 'CardUser', 'ID', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Carduser', 'Carduser', RelationMap::MANY_TO_ONE, array('owner' => 'id', ), null, null);
    $this->addRelation('Subscription', 'Subscription', RelationMap::ONE_TO_MANY, array('id' => 'Card_id', ), 'CASCADE', null);
    $this->addRelation('Reservation', 'Reservation', RelationMap::ONE_TO_MANY, array('id' => 'Card_id', ), 'CASCADE', null);
	} // buildRelations()

} // CardTableMap
