<?php


/**
 * This class defines the structure of the 'EnergyAction' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Sep 30 06:33:12 2010
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class EnergyactionTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.EnergyactionTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('EnergyAction');
		$this->setPhpName('Energyaction');
		$this->setClassname('Energyaction');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('NAME', 'Name', 'VARCHAR', true, 64, null);
		$this->addColumn('DELAYUP', 'Delayup', 'INTEGER', true, null, 0);
		$this->addColumn('DELAYDOWN', 'Delaydown', 'INTEGER', true, null, 0);
		$this->addColumn('IDENTIFIER', 'Identifier', 'VARCHAR', false, 64, null);
		$this->addColumn('PROCESSIDUP', 'Processidup', 'VARCHAR', false, 64, null);
		$this->addColumn('PROCESSIDDOWN', 'Processiddown', 'VARCHAR', false, 64, null);
		$this->addColumn('START', 'Start', 'TIME', true, null, null);
		$this->addColumn('STOP', 'Stop', 'TIME', true, null, null);
		$this->addColumn('STATUS', 'Status', 'BOOLEAN', true, null, false);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('RoomHasEnergyaction', 'RoomHasEnergyaction', RelationMap::ONE_TO_MANY, array('id' => 'EnergyAction_id', ), 'CASCADE', null);
	} // buildRelations()

} // EnergyactionTableMap
