<?php


/**
 * This class adds structure of 'Message' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 19/12/2012 10:11:00
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class MessageMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.MessageMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(MessagePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(MessagePeer::TABLE_NAME);
		$tMap->setPhpName('Message');
		$tMap->setClassname('Message');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11);

		$tMap->addColumn('SUBJECT', 'Subject', 'VARCHAR', true, 256);

		$tMap->addColumn('TEXT', 'Text', 'LONGVARCHAR', true, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addForeignKey('RECIPIENT_ID', 'RecipientId', 'INTEGER', 'User', 'ID', true, 11);

		$tMap->addColumn('SENDER', 'Sender', 'VARCHAR', true, 256);

		$tMap->addForeignKey('SENDER_ID', 'SenderId', 'INTEGER', 'User', 'ID', false, 11);

		$tMap->addColumn('WAS_READ', 'WasRead', 'TINYINT', true, 4);

		$tMap->addForeignKey('OWNER_ID', 'OwnerId', 'INTEGER', 'User', 'ID', true, 11);

	} // doBuild()

} // MessageMapBuilder
