<?php

/**
 * Base class that represents a row from the 'Subscription' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 19/12/2012 10:11:01
 *
 * @package    lib.model.om
 */
abstract class BaseSubscription extends BaseObject  implements Persistent {


  const PEER = 'SubscriptionPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        SubscriptionPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the activity_id field.
	 * @var        int
	 */
	protected $activity_id;

	/**
	 * The value for the zone_id field.
	 * @var        int
	 */
	protected $zone_id;

	/**
	 * The value for the start field.
	 * @var        string
	 */
	protected $start;

	/**
	 * The value for the stop field.
	 * @var        string
	 */
	protected $stop;

	/**
	 * The value for the credit field.
	 * @var        int
	 */
	protected $credit;

	/**
	 * The value for the is_active field.
	 * Note: this column has a database default value of: 1
	 * @var        int
	 */
	protected $is_active;

	/**
	 * The value for the card_id field.
	 * @var        int
	 */
	protected $card_id;

	/**
	 * The value for the user_id field.
	 * @var        int
	 */
	protected $user_id;

	/**
	 * The value for the minimum_delay field.
	 * Note: this column has a database default value of: 12
	 * @var        int
	 */
	protected $minimum_delay;

	/**
	 * The value for the maximum_delay field.
	 * Note: this column has a database default value of: 7
	 * @var        int
	 */
	protected $maximum_delay;

	/**
	 * The value for the maximum_duration field.
	 * Note: this column has a database default value of: 120
	 * @var        int
	 */
	protected $maximum_duration;

	/**
	 * The value for the hours_per_week field.
	 * Note: this column has a database default value of: 4
	 * @var        int
	 */
	protected $hours_per_week;

	/**
	 * The value for the usergroup_id field.
	 * @var        int
	 */
	protected $usergroup_id;

	/**
	 * The value for the minimum_duration field.
	 * Note: this column has a database default value of: 60
	 * @var        int
	 */
	protected $minimum_duration;

	/**
	 * @var        Activity
	 */
	protected $aActivity;

	/**
	 * @var        Zone
	 */
	protected $aZone;

	/**
	 * @var        Card
	 */
	protected $aCard;

	/**
	 * @var        User
	 */
	protected $aUser;

	/**
	 * @var        Usergroup
	 */
	protected $aUsergroup;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseSubscription object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->is_active = 1;
		$this->minimum_delay = 12;
		$this->maximum_delay = 7;
		$this->maximum_duration = 120;
		$this->hours_per_week = 4;
		$this->minimum_duration = 60;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [activity_id] column value.
	 * 
	 * @return     int
	 */
	public function getActivityId()
	{
		return $this->activity_id;
	}

	/**
	 * Get the [zone_id] column value.
	 * 
	 * @return     int
	 */
	public function getZoneId()
	{
		return $this->zone_id;
	}

	/**
	 * Get the [optionally formatted] temporal [start] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getStart($format = 'Y-m-d')
	{
		if ($this->start === null) {
			return null;
		}


		if ($this->start === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->start);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->start, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [stop] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getStop($format = 'Y-m-d')
	{
		if ($this->stop === null) {
			return null;
		}


		if ($this->stop === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->stop);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->stop, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [credit] column value.
	 * 
	 * @return     int
	 */
	public function getCredit()
	{
		return $this->credit;
	}

	/**
	 * Get the [is_active] column value.
	 * 
	 * @return     int
	 */
	public function getIsActive()
	{
		return $this->is_active;
	}

	/**
	 * Get the [card_id] column value.
	 * 
	 * @return     int
	 */
	public function getCardId()
	{
		return $this->card_id;
	}

	/**
	 * Get the [user_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Get the [minimum_delay] column value.
	 * 
	 * @return     int
	 */
	public function getMinimumDelay()
	{
		return $this->minimum_delay;
	}

	/**
	 * Get the [maximum_delay] column value.
	 * 
	 * @return     int
	 */
	public function getMaximumDelay()
	{
		return $this->maximum_delay;
	}

	/**
	 * Get the [maximum_duration] column value.
	 * 
	 * @return     int
	 */
	public function getMaximumDuration()
	{
		return $this->maximum_duration;
	}

	/**
	 * Get the [hours_per_week] column value.
	 * 
	 * @return     int
	 */
	public function getHoursPerWeek()
	{
		return $this->hours_per_week;
	}

	/**
	 * Get the [usergroup_id] column value.
	 * 
	 * @return     int
	 */
	public function getUsergroupId()
	{
		return $this->usergroup_id;
	}

	/**
	 * Get the [minimum_duration] column value.
	 * 
	 * @return     int
	 */
	public function getMinimumDuration()
	{
		return $this->minimum_duration;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Subscription The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = SubscriptionPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [activity_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Subscription The current object (for fluent API support)
	 */
	public function setActivityId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->activity_id !== $v) {
			$this->activity_id = $v;
			$this->modifiedColumns[] = SubscriptionPeer::ACTIVITY_ID;
		}

		if ($this->aActivity !== null && $this->aActivity->getId() !== $v) {
			$this->aActivity = null;
		}

		return $this;
	} // setActivityId()

	/**
	 * Set the value of [zone_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Subscription The current object (for fluent API support)
	 */
	public function setZoneId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->zone_id !== $v) {
			$this->zone_id = $v;
			$this->modifiedColumns[] = SubscriptionPeer::ZONE_ID;
		}

		if ($this->aZone !== null && $this->aZone->getId() !== $v) {
			$this->aZone = null;
		}

		return $this;
	} // setZoneId()

	/**
	 * Sets the value of [start] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Subscription The current object (for fluent API support)
	 */
	public function setStart($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->start !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->start !== null && $tmpDt = new DateTime($this->start)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->start = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = SubscriptionPeer::START;
			}
		} // if either are not null

		return $this;
	} // setStart()

	/**
	 * Sets the value of [stop] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Subscription The current object (for fluent API support)
	 */
	public function setStop($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->stop !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->stop !== null && $tmpDt = new DateTime($this->stop)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->stop = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = SubscriptionPeer::STOP;
			}
		} // if either are not null

		return $this;
	} // setStop()

	/**
	 * Set the value of [credit] column.
	 * 
	 * @param      int $v new value
	 * @return     Subscription The current object (for fluent API support)
	 */
	public function setCredit($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->credit !== $v) {
			$this->credit = $v;
			$this->modifiedColumns[] = SubscriptionPeer::CREDIT;
		}

		return $this;
	} // setCredit()

	/**
	 * Set the value of [is_active] column.
	 * 
	 * @param      int $v new value
	 * @return     Subscription The current object (for fluent API support)
	 */
	public function setIsActive($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->is_active !== $v || $v === 1) {
			$this->is_active = $v;
			$this->modifiedColumns[] = SubscriptionPeer::IS_ACTIVE;
		}

		return $this;
	} // setIsActive()

	/**
	 * Set the value of [card_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Subscription The current object (for fluent API support)
	 */
	public function setCardId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->card_id !== $v) {
			$this->card_id = $v;
			$this->modifiedColumns[] = SubscriptionPeer::CARD_ID;
		}

		if ($this->aCard !== null && $this->aCard->getId() !== $v) {
			$this->aCard = null;
		}

		return $this;
	} // setCardId()

	/**
	 * Set the value of [user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Subscription The current object (for fluent API support)
	 */
	public function setUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_id !== $v) {
			$this->user_id = $v;
			$this->modifiedColumns[] = SubscriptionPeer::USER_ID;
		}

		if ($this->aUser !== null && $this->aUser->getId() !== $v) {
			$this->aUser = null;
		}

		return $this;
	} // setUserId()

	/**
	 * Set the value of [minimum_delay] column.
	 * 
	 * @param      int $v new value
	 * @return     Subscription The current object (for fluent API support)
	 */
	public function setMinimumDelay($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->minimum_delay !== $v || $v === 12) {
			$this->minimum_delay = $v;
			$this->modifiedColumns[] = SubscriptionPeer::MINIMUM_DELAY;
		}

		return $this;
	} // setMinimumDelay()

	/**
	 * Set the value of [maximum_delay] column.
	 * 
	 * @param      int $v new value
	 * @return     Subscription The current object (for fluent API support)
	 */
	public function setMaximumDelay($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->maximum_delay !== $v || $v === 7) {
			$this->maximum_delay = $v;
			$this->modifiedColumns[] = SubscriptionPeer::MAXIMUM_DELAY;
		}

		return $this;
	} // setMaximumDelay()

	/**
	 * Set the value of [maximum_duration] column.
	 * 
	 * @param      int $v new value
	 * @return     Subscription The current object (for fluent API support)
	 */
	public function setMaximumDuration($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->maximum_duration !== $v || $v === 120) {
			$this->maximum_duration = $v;
			$this->modifiedColumns[] = SubscriptionPeer::MAXIMUM_DURATION;
		}

		return $this;
	} // setMaximumDuration()

	/**
	 * Set the value of [hours_per_week] column.
	 * 
	 * @param      int $v new value
	 * @return     Subscription The current object (for fluent API support)
	 */
	public function setHoursPerWeek($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->hours_per_week !== $v || $v === 4) {
			$this->hours_per_week = $v;
			$this->modifiedColumns[] = SubscriptionPeer::HOURS_PER_WEEK;
		}

		return $this;
	} // setHoursPerWeek()

	/**
	 * Set the value of [usergroup_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Subscription The current object (for fluent API support)
	 */
	public function setUsergroupId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->usergroup_id !== $v) {
			$this->usergroup_id = $v;
			$this->modifiedColumns[] = SubscriptionPeer::USERGROUP_ID;
		}

		if ($this->aUsergroup !== null && $this->aUsergroup->getId() !== $v) {
			$this->aUsergroup = null;
		}

		return $this;
	} // setUsergroupId()

	/**
	 * Set the value of [minimum_duration] column.
	 * 
	 * @param      int $v new value
	 * @return     Subscription The current object (for fluent API support)
	 */
	public function setMinimumDuration($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->minimum_duration !== $v || $v === 60) {
			$this->minimum_duration = $v;
			$this->modifiedColumns[] = SubscriptionPeer::MINIMUM_DURATION;
		}

		return $this;
	} // setMinimumDuration()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(SubscriptionPeer::IS_ACTIVE,SubscriptionPeer::MINIMUM_DELAY,SubscriptionPeer::MAXIMUM_DELAY,SubscriptionPeer::MAXIMUM_DURATION,SubscriptionPeer::HOURS_PER_WEEK,SubscriptionPeer::MINIMUM_DURATION))) {
				return false;
			}

			if ($this->is_active !== 1) {
				return false;
			}

			if ($this->minimum_delay !== 12) {
				return false;
			}

			if ($this->maximum_delay !== 7) {
				return false;
			}

			if ($this->maximum_duration !== 120) {
				return false;
			}

			if ($this->hours_per_week !== 4) {
				return false;
			}

			if ($this->minimum_duration !== 60) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->activity_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->zone_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->start = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->stop = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->credit = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->is_active = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->card_id = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->user_id = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->minimum_delay = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->maximum_delay = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->maximum_duration = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->hours_per_week = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->usergroup_id = ($row[$startcol + 13] !== null) ? (int) $row[$startcol + 13] : null;
			$this->minimum_duration = ($row[$startcol + 14] !== null) ? (int) $row[$startcol + 14] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 15; // 15 = SubscriptionPeer::NUM_COLUMNS - SubscriptionPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Subscription object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aActivity !== null && $this->activity_id !== $this->aActivity->getId()) {
			$this->aActivity = null;
		}
		if ($this->aZone !== null && $this->zone_id !== $this->aZone->getId()) {
			$this->aZone = null;
		}
		if ($this->aCard !== null && $this->card_id !== $this->aCard->getId()) {
			$this->aCard = null;
		}
		if ($this->aUser !== null && $this->user_id !== $this->aUser->getId()) {
			$this->aUser = null;
		}
		if ($this->aUsergroup !== null && $this->usergroup_id !== $this->aUsergroup->getId()) {
			$this->aUsergroup = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SubscriptionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = SubscriptionPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aActivity = null;
			$this->aZone = null;
			$this->aCard = null;
			$this->aUser = null;
			$this->aUsergroup = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseSubscription:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SubscriptionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			SubscriptionPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseSubscription:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseSubscription:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SubscriptionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseSubscription:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			SubscriptionPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aActivity !== null) {
				if ($this->aActivity->isModified() || $this->aActivity->isNew()) {
					$affectedRows += $this->aActivity->save($con);
				}
				$this->setActivity($this->aActivity);
			}

			if ($this->aZone !== null) {
				if ($this->aZone->isModified() || $this->aZone->isNew()) {
					$affectedRows += $this->aZone->save($con);
				}
				$this->setZone($this->aZone);
			}

			if ($this->aCard !== null) {
				if ($this->aCard->isModified() || $this->aCard->isNew()) {
					$affectedRows += $this->aCard->save($con);
				}
				$this->setCard($this->aCard);
			}

			if ($this->aUser !== null) {
				if ($this->aUser->isModified() || $this->aUser->isNew()) {
					$affectedRows += $this->aUser->save($con);
				}
				$this->setUser($this->aUser);
			}

			if ($this->aUsergroup !== null) {
				if ($this->aUsergroup->isModified() || $this->aUsergroup->isNew()) {
					$affectedRows += $this->aUsergroup->save($con);
				}
				$this->setUsergroup($this->aUsergroup);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = SubscriptionPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = SubscriptionPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += SubscriptionPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aActivity !== null) {
				if (!$this->aActivity->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aActivity->getValidationFailures());
				}
			}

			if ($this->aZone !== null) {
				if (!$this->aZone->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aZone->getValidationFailures());
				}
			}

			if ($this->aCard !== null) {
				if (!$this->aCard->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCard->getValidationFailures());
				}
			}

			if ($this->aUser !== null) {
				if (!$this->aUser->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUser->getValidationFailures());
				}
			}

			if ($this->aUsergroup !== null) {
				if (!$this->aUsergroup->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsergroup->getValidationFailures());
				}
			}


			if (($retval = SubscriptionPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = SubscriptionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getActivityId();
				break;
			case 2:
				return $this->getZoneId();
				break;
			case 3:
				return $this->getStart();
				break;
			case 4:
				return $this->getStop();
				break;
			case 5:
				return $this->getCredit();
				break;
			case 6:
				return $this->getIsActive();
				break;
			case 7:
				return $this->getCardId();
				break;
			case 8:
				return $this->getUserId();
				break;
			case 9:
				return $this->getMinimumDelay();
				break;
			case 10:
				return $this->getMaximumDelay();
				break;
			case 11:
				return $this->getMaximumDuration();
				break;
			case 12:
				return $this->getHoursPerWeek();
				break;
			case 13:
				return $this->getUsergroupId();
				break;
			case 14:
				return $this->getMinimumDuration();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = SubscriptionPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getActivityId(),
			$keys[2] => $this->getZoneId(),
			$keys[3] => $this->getStart(),
			$keys[4] => $this->getStop(),
			$keys[5] => $this->getCredit(),
			$keys[6] => $this->getIsActive(),
			$keys[7] => $this->getCardId(),
			$keys[8] => $this->getUserId(),
			$keys[9] => $this->getMinimumDelay(),
			$keys[10] => $this->getMaximumDelay(),
			$keys[11] => $this->getMaximumDuration(),
			$keys[12] => $this->getHoursPerWeek(),
			$keys[13] => $this->getUsergroupId(),
			$keys[14] => $this->getMinimumDuration(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = SubscriptionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setActivityId($value);
				break;
			case 2:
				$this->setZoneId($value);
				break;
			case 3:
				$this->setStart($value);
				break;
			case 4:
				$this->setStop($value);
				break;
			case 5:
				$this->setCredit($value);
				break;
			case 6:
				$this->setIsActive($value);
				break;
			case 7:
				$this->setCardId($value);
				break;
			case 8:
				$this->setUserId($value);
				break;
			case 9:
				$this->setMinimumDelay($value);
				break;
			case 10:
				$this->setMaximumDelay($value);
				break;
			case 11:
				$this->setMaximumDuration($value);
				break;
			case 12:
				$this->setHoursPerWeek($value);
				break;
			case 13:
				$this->setUsergroupId($value);
				break;
			case 14:
				$this->setMinimumDuration($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = SubscriptionPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setActivityId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setZoneId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setStart($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setStop($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setCredit($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setIsActive($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setCardId($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setUserId($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setMinimumDelay($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setMaximumDelay($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setMaximumDuration($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setHoursPerWeek($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setUsergroupId($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setMinimumDuration($arr[$keys[14]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(SubscriptionPeer::DATABASE_NAME);

		if ($this->isColumnModified(SubscriptionPeer::ID)) $criteria->add(SubscriptionPeer::ID, $this->id);
		if ($this->isColumnModified(SubscriptionPeer::ACTIVITY_ID)) $criteria->add(SubscriptionPeer::ACTIVITY_ID, $this->activity_id);
		if ($this->isColumnModified(SubscriptionPeer::ZONE_ID)) $criteria->add(SubscriptionPeer::ZONE_ID, $this->zone_id);
		if ($this->isColumnModified(SubscriptionPeer::START)) $criteria->add(SubscriptionPeer::START, $this->start);
		if ($this->isColumnModified(SubscriptionPeer::STOP)) $criteria->add(SubscriptionPeer::STOP, $this->stop);
		if ($this->isColumnModified(SubscriptionPeer::CREDIT)) $criteria->add(SubscriptionPeer::CREDIT, $this->credit);
		if ($this->isColumnModified(SubscriptionPeer::IS_ACTIVE)) $criteria->add(SubscriptionPeer::IS_ACTIVE, $this->is_active);
		if ($this->isColumnModified(SubscriptionPeer::CARD_ID)) $criteria->add(SubscriptionPeer::CARD_ID, $this->card_id);
		if ($this->isColumnModified(SubscriptionPeer::USER_ID)) $criteria->add(SubscriptionPeer::USER_ID, $this->user_id);
		if ($this->isColumnModified(SubscriptionPeer::MINIMUM_DELAY)) $criteria->add(SubscriptionPeer::MINIMUM_DELAY, $this->minimum_delay);
		if ($this->isColumnModified(SubscriptionPeer::MAXIMUM_DELAY)) $criteria->add(SubscriptionPeer::MAXIMUM_DELAY, $this->maximum_delay);
		if ($this->isColumnModified(SubscriptionPeer::MAXIMUM_DURATION)) $criteria->add(SubscriptionPeer::MAXIMUM_DURATION, $this->maximum_duration);
		if ($this->isColumnModified(SubscriptionPeer::HOURS_PER_WEEK)) $criteria->add(SubscriptionPeer::HOURS_PER_WEEK, $this->hours_per_week);
		if ($this->isColumnModified(SubscriptionPeer::USERGROUP_ID)) $criteria->add(SubscriptionPeer::USERGROUP_ID, $this->usergroup_id);
		if ($this->isColumnModified(SubscriptionPeer::MINIMUM_DURATION)) $criteria->add(SubscriptionPeer::MINIMUM_DURATION, $this->minimum_duration);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(SubscriptionPeer::DATABASE_NAME);

		$criteria->add(SubscriptionPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Subscription (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setActivityId($this->activity_id);

		$copyObj->setZoneId($this->zone_id);

		$copyObj->setStart($this->start);

		$copyObj->setStop($this->stop);

		$copyObj->setCredit($this->credit);

		$copyObj->setIsActive($this->is_active);

		$copyObj->setCardId($this->card_id);

		$copyObj->setUserId($this->user_id);

		$copyObj->setMinimumDelay($this->minimum_delay);

		$copyObj->setMaximumDelay($this->maximum_delay);

		$copyObj->setMaximumDuration($this->maximum_duration);

		$copyObj->setHoursPerWeek($this->hours_per_week);

		$copyObj->setUsergroupId($this->usergroup_id);

		$copyObj->setMinimumDuration($this->minimum_duration);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Subscription Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     SubscriptionPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new SubscriptionPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Activity object.
	 *
	 * @param      Activity $v
	 * @return     Subscription The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setActivity(Activity $v = null)
	{
		if ($v === null) {
			$this->setActivityId(NULL);
		} else {
			$this->setActivityId($v->getId());
		}

		$this->aActivity = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Activity object, it will not be re-added.
		if ($v !== null) {
			$v->addSubscription($this);
		}

		return $this;
	}


	/**
	 * Get the associated Activity object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Activity The associated Activity object.
	 * @throws     PropelException
	 */
	public function getActivity(PropelPDO $con = null)
	{
		if ($this->aActivity === null && ($this->activity_id !== null)) {
			$c = new Criteria(ActivityPeer::DATABASE_NAME);
			$c->add(ActivityPeer::ID, $this->activity_id);
			$this->aActivity = ActivityPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aActivity->addSubscriptions($this);
			 */
		}
		return $this->aActivity;
	}

	/**
	 * Declares an association between this object and a Zone object.
	 *
	 * @param      Zone $v
	 * @return     Subscription The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setZone(Zone $v = null)
	{
		if ($v === null) {
			$this->setZoneId(NULL);
		} else {
			$this->setZoneId($v->getId());
		}

		$this->aZone = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Zone object, it will not be re-added.
		if ($v !== null) {
			$v->addSubscription($this);
		}

		return $this;
	}


	/**
	 * Get the associated Zone object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Zone The associated Zone object.
	 * @throws     PropelException
	 */
	public function getZone(PropelPDO $con = null)
	{
		if ($this->aZone === null && ($this->zone_id !== null)) {
			$c = new Criteria(ZonePeer::DATABASE_NAME);
			$c->add(ZonePeer::ID, $this->zone_id);
			$this->aZone = ZonePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aZone->addSubscriptions($this);
			 */
		}
		return $this->aZone;
	}

	/**
	 * Declares an association between this object and a Card object.
	 *
	 * @param      Card $v
	 * @return     Subscription The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCard(Card $v = null)
	{
		if ($v === null) {
			$this->setCardId(NULL);
		} else {
			$this->setCardId($v->getId());
		}

		$this->aCard = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Card object, it will not be re-added.
		if ($v !== null) {
			$v->addSubscription($this);
		}

		return $this;
	}


	/**
	 * Get the associated Card object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Card The associated Card object.
	 * @throws     PropelException
	 */
	public function getCard(PropelPDO $con = null)
	{
		if ($this->aCard === null && ($this->card_id !== null)) {
			$c = new Criteria(CardPeer::DATABASE_NAME);
			$c->add(CardPeer::ID, $this->card_id);
			$this->aCard = CardPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCard->addSubscriptions($this);
			 */
		}
		return $this->aCard;
	}

	/**
	 * Declares an association between this object and a User object.
	 *
	 * @param      User $v
	 * @return     Subscription The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUser(User $v = null)
	{
		if ($v === null) {
			$this->setUserId(NULL);
		} else {
			$this->setUserId($v->getId());
		}

		$this->aUser = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the User object, it will not be re-added.
		if ($v !== null) {
			$v->addSubscription($this);
		}

		return $this;
	}


	/**
	 * Get the associated User object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     User The associated User object.
	 * @throws     PropelException
	 */
	public function getUser(PropelPDO $con = null)
	{
		if ($this->aUser === null && ($this->user_id !== null)) {
			$c = new Criteria(UserPeer::DATABASE_NAME);
			$c->add(UserPeer::ID, $this->user_id);
			$this->aUser = UserPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUser->addSubscriptions($this);
			 */
		}
		return $this->aUser;
	}

	/**
	 * Declares an association between this object and a Usergroup object.
	 *
	 * @param      Usergroup $v
	 * @return     Subscription The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsergroup(Usergroup $v = null)
	{
		if ($v === null) {
			$this->setUsergroupId(NULL);
		} else {
			$this->setUsergroupId($v->getId());
		}

		$this->aUsergroup = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Usergroup object, it will not be re-added.
		if ($v !== null) {
			$v->addSubscription($this);
		}

		return $this;
	}


	/**
	 * Get the associated Usergroup object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Usergroup The associated Usergroup object.
	 * @throws     PropelException
	 */
	public function getUsergroup(PropelPDO $con = null)
	{
		if ($this->aUsergroup === null && ($this->usergroup_id !== null)) {
			$c = new Criteria(UsergroupPeer::DATABASE_NAME);
			$c->add(UsergroupPeer::ID, $this->usergroup_id);
			$this->aUsergroup = UsergroupPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsergroup->addSubscriptions($this);
			 */
		}
		return $this->aUsergroup;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aActivity = null;
			$this->aZone = null;
			$this->aCard = null;
			$this->aUser = null;
			$this->aUsergroup = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseSubscription:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseSubscription::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseSubscription
