<?php

/**
 * Base class that represents a row from the 'UserGroup' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 19/12/2012 10:11:01
 *
 * @package    lib.model.om
 */
abstract class BaseUsergroup extends BaseObject  implements Persistent {


  const PEER = 'UsergroupPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        UsergroupPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * @var        array Reservation[] Collection to store aggregation of Reservation objects.
	 */
	protected $collReservations;

	/**
	 * @var        Criteria The criteria used to select the current contents of collReservations.
	 */
	private $lastReservationCriteria = null;

	/**
	 * @var        array Subscription[] Collection to store aggregation of Subscription objects.
	 */
	protected $collSubscriptions;

	/**
	 * @var        Criteria The criteria used to select the current contents of collSubscriptions.
	 */
	private $lastSubscriptionCriteria = null;

	/**
	 * @var        array UsergroupHasActivity[] Collection to store aggregation of UsergroupHasActivity objects.
	 */
	protected $collUsergroupHasActivitys;

	/**
	 * @var        Criteria The criteria used to select the current contents of collUsergroupHasActivitys.
	 */
	private $lastUsergroupHasActivityCriteria = null;

	/**
	 * @var        array UsergroupHasChief[] Collection to store aggregation of UsergroupHasChief objects.
	 */
	protected $collUsergroupHasChiefs;

	/**
	 * @var        Criteria The criteria used to select the current contents of collUsergroupHasChiefs.
	 */
	private $lastUsergroupHasChiefCriteria = null;

	/**
	 * @var        array UsergroupHasUser[] Collection to store aggregation of UsergroupHasUser objects.
	 */
	protected $collUsergroupHasUsers;

	/**
	 * @var        Criteria The criteria used to select the current contents of collUsergroupHasUsers.
	 */
	private $lastUsergroupHasUserCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseUsergroup object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Usergroup The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = UsergroupPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     Usergroup The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = UsergroupPeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 2; // 2 = UsergroupPeer::NUM_COLUMNS - UsergroupPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Usergroup object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UsergroupPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = UsergroupPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collReservations = null;
			$this->lastReservationCriteria = null;

			$this->collSubscriptions = null;
			$this->lastSubscriptionCriteria = null;

			$this->collUsergroupHasActivitys = null;
			$this->lastUsergroupHasActivityCriteria = null;

			$this->collUsergroupHasChiefs = null;
			$this->lastUsergroupHasChiefCriteria = null;

			$this->collUsergroupHasUsers = null;
			$this->lastUsergroupHasUserCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUsergroup:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UsergroupPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			UsergroupPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseUsergroup:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUsergroup:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UsergroupPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseUsergroup:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			UsergroupPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = UsergroupPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = UsergroupPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += UsergroupPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collReservations !== null) {
				foreach ($this->collReservations as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collSubscriptions !== null) {
				foreach ($this->collSubscriptions as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collUsergroupHasActivitys !== null) {
				foreach ($this->collUsergroupHasActivitys as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collUsergroupHasChiefs !== null) {
				foreach ($this->collUsergroupHasChiefs as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collUsergroupHasUsers !== null) {
				foreach ($this->collUsergroupHasUsers as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = UsergroupPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collReservations !== null) {
					foreach ($this->collReservations as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collSubscriptions !== null) {
					foreach ($this->collSubscriptions as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collUsergroupHasActivitys !== null) {
					foreach ($this->collUsergroupHasActivitys as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collUsergroupHasChiefs !== null) {
					foreach ($this->collUsergroupHasChiefs as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collUsergroupHasUsers !== null) {
					foreach ($this->collUsergroupHasUsers as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UsergroupPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getName();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = UsergroupPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getName(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UsergroupPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setName($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = UsergroupPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setName($arr[$keys[1]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);

		if ($this->isColumnModified(UsergroupPeer::ID)) $criteria->add(UsergroupPeer::ID, $this->id);
		if ($this->isColumnModified(UsergroupPeer::NAME)) $criteria->add(UsergroupPeer::NAME, $this->name);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);

		$criteria->add(UsergroupPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Usergroup (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setName($this->name);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getReservations() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addReservation($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getSubscriptions() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addSubscription($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getUsergroupHasActivitys() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addUsergroupHasActivity($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getUsergroupHasChiefs() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addUsergroupHasChief($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getUsergroupHasUsers() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addUsergroupHasUser($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Usergroup Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     UsergroupPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new UsergroupPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collReservations collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addReservations()
	 */
	public function clearReservations()
	{
		$this->collReservations = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collReservations collection (array).
	 *
	 * By default this just sets the collReservations collection to an empty array (like clearcollReservations());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initReservations()
	{
		$this->collReservations = array();
	}

	/**
	 * Gets an array of Reservation objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Usergroup has previously been saved, it will retrieve
	 * related Reservations from storage. If this Usergroup is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Reservation[]
	 * @throws     PropelException
	 */
	public function getReservations($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collReservations === null) {
			if ($this->isNew()) {
			   $this->collReservations = array();
			} else {

				$criteria->add(ReservationPeer::USERGROUP_ID, $this->id);

				ReservationPeer::addSelectColumns($criteria);
				$this->collReservations = ReservationPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ReservationPeer::USERGROUP_ID, $this->id);

				ReservationPeer::addSelectColumns($criteria);
				if (!isset($this->lastReservationCriteria) || !$this->lastReservationCriteria->equals($criteria)) {
					$this->collReservations = ReservationPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastReservationCriteria = $criteria;
		return $this->collReservations;
	}

	/**
	 * Returns the number of related Reservation objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Reservation objects.
	 * @throws     PropelException
	 */
	public function countReservations(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collReservations === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ReservationPeer::USERGROUP_ID, $this->id);

				$count = ReservationPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ReservationPeer::USERGROUP_ID, $this->id);

				if (!isset($this->lastReservationCriteria) || !$this->lastReservationCriteria->equals($criteria)) {
					$count = ReservationPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collReservations);
				}
			} else {
				$count = count($this->collReservations);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Reservation object to this object
	 * through the Reservation foreign key attribute.
	 *
	 * @param      Reservation $l Reservation
	 * @return     void
	 * @throws     PropelException
	 */
	public function addReservation(Reservation $l)
	{
		if ($this->collReservations === null) {
			$this->initReservations();
		}
		if (!in_array($l, $this->collReservations, true)) { // only add it if the **same** object is not already associated
			array_push($this->collReservations, $l);
			$l->setUsergroup($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Usergroup is new, it will return
	 * an empty collection; or if this Usergroup has previously
	 * been saved, it will retrieve related Reservations from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Usergroup.
	 */
	public function getReservationsJoinRoomprofile($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collReservations === null) {
			if ($this->isNew()) {
				$this->collReservations = array();
			} else {

				$criteria->add(ReservationPeer::USERGROUP_ID, $this->id);

				$this->collReservations = ReservationPeer::doSelectJoinRoomprofile($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ReservationPeer::USERGROUP_ID, $this->id);

			if (!isset($this->lastReservationCriteria) || !$this->lastReservationCriteria->equals($criteria)) {
				$this->collReservations = ReservationPeer::doSelectJoinRoomprofile($criteria, $con, $join_behavior);
			}
		}
		$this->lastReservationCriteria = $criteria;

		return $this->collReservations;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Usergroup is new, it will return
	 * an empty collection; or if this Usergroup has previously
	 * been saved, it will retrieve related Reservations from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Usergroup.
	 */
	public function getReservationsJoinActivity($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collReservations === null) {
			if ($this->isNew()) {
				$this->collReservations = array();
			} else {

				$criteria->add(ReservationPeer::USERGROUP_ID, $this->id);

				$this->collReservations = ReservationPeer::doSelectJoinActivity($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ReservationPeer::USERGROUP_ID, $this->id);

			if (!isset($this->lastReservationCriteria) || !$this->lastReservationCriteria->equals($criteria)) {
				$this->collReservations = ReservationPeer::doSelectJoinActivity($criteria, $con, $join_behavior);
			}
		}
		$this->lastReservationCriteria = $criteria;

		return $this->collReservations;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Usergroup is new, it will return
	 * an empty collection; or if this Usergroup has previously
	 * been saved, it will retrieve related Reservations from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Usergroup.
	 */
	public function getReservationsJoinReservationreason($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collReservations === null) {
			if ($this->isNew()) {
				$this->collReservations = array();
			} else {

				$criteria->add(ReservationPeer::USERGROUP_ID, $this->id);

				$this->collReservations = ReservationPeer::doSelectJoinReservationreason($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ReservationPeer::USERGROUP_ID, $this->id);

			if (!isset($this->lastReservationCriteria) || !$this->lastReservationCriteria->equals($criteria)) {
				$this->collReservations = ReservationPeer::doSelectJoinReservationreason($criteria, $con, $join_behavior);
			}
		}
		$this->lastReservationCriteria = $criteria;

		return $this->collReservations;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Usergroup is new, it will return
	 * an empty collection; or if this Usergroup has previously
	 * been saved, it will retrieve related Reservations from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Usergroup.
	 */
	public function getReservationsJoinCard($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collReservations === null) {
			if ($this->isNew()) {
				$this->collReservations = array();
			} else {

				$criteria->add(ReservationPeer::USERGROUP_ID, $this->id);

				$this->collReservations = ReservationPeer::doSelectJoinCard($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ReservationPeer::USERGROUP_ID, $this->id);

			if (!isset($this->lastReservationCriteria) || !$this->lastReservationCriteria->equals($criteria)) {
				$this->collReservations = ReservationPeer::doSelectJoinCard($criteria, $con, $join_behavior);
			}
		}
		$this->lastReservationCriteria = $criteria;

		return $this->collReservations;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Usergroup is new, it will return
	 * an empty collection; or if this Usergroup has previously
	 * been saved, it will retrieve related Reservations from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Usergroup.
	 */
	public function getReservationsJoinUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collReservations === null) {
			if ($this->isNew()) {
				$this->collReservations = array();
			} else {

				$criteria->add(ReservationPeer::USERGROUP_ID, $this->id);

				$this->collReservations = ReservationPeer::doSelectJoinUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ReservationPeer::USERGROUP_ID, $this->id);

			if (!isset($this->lastReservationCriteria) || !$this->lastReservationCriteria->equals($criteria)) {
				$this->collReservations = ReservationPeer::doSelectJoinUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastReservationCriteria = $criteria;

		return $this->collReservations;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Usergroup is new, it will return
	 * an empty collection; or if this Usergroup has previously
	 * been saved, it will retrieve related Reservations from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Usergroup.
	 */
	public function getReservationsJoinReservationRelatedByReservationparentId($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collReservations === null) {
			if ($this->isNew()) {
				$this->collReservations = array();
			} else {

				$criteria->add(ReservationPeer::USERGROUP_ID, $this->id);

				$this->collReservations = ReservationPeer::doSelectJoinReservationRelatedByReservationparentId($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ReservationPeer::USERGROUP_ID, $this->id);

			if (!isset($this->lastReservationCriteria) || !$this->lastReservationCriteria->equals($criteria)) {
				$this->collReservations = ReservationPeer::doSelectJoinReservationRelatedByReservationparentId($criteria, $con, $join_behavior);
			}
		}
		$this->lastReservationCriteria = $criteria;

		return $this->collReservations;
	}

	/**
	 * Clears out the collSubscriptions collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addSubscriptions()
	 */
	public function clearSubscriptions()
	{
		$this->collSubscriptions = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collSubscriptions collection (array).
	 *
	 * By default this just sets the collSubscriptions collection to an empty array (like clearcollSubscriptions());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initSubscriptions()
	{
		$this->collSubscriptions = array();
	}

	/**
	 * Gets an array of Subscription objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Usergroup has previously been saved, it will retrieve
	 * related Subscriptions from storage. If this Usergroup is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Subscription[]
	 * @throws     PropelException
	 */
	public function getSubscriptions($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSubscriptions === null) {
			if ($this->isNew()) {
			   $this->collSubscriptions = array();
			} else {

				$criteria->add(SubscriptionPeer::USERGROUP_ID, $this->id);

				SubscriptionPeer::addSelectColumns($criteria);
				$this->collSubscriptions = SubscriptionPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(SubscriptionPeer::USERGROUP_ID, $this->id);

				SubscriptionPeer::addSelectColumns($criteria);
				if (!isset($this->lastSubscriptionCriteria) || !$this->lastSubscriptionCriteria->equals($criteria)) {
					$this->collSubscriptions = SubscriptionPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastSubscriptionCriteria = $criteria;
		return $this->collSubscriptions;
	}

	/**
	 * Returns the number of related Subscription objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Subscription objects.
	 * @throws     PropelException
	 */
	public function countSubscriptions(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collSubscriptions === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(SubscriptionPeer::USERGROUP_ID, $this->id);

				$count = SubscriptionPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(SubscriptionPeer::USERGROUP_ID, $this->id);

				if (!isset($this->lastSubscriptionCriteria) || !$this->lastSubscriptionCriteria->equals($criteria)) {
					$count = SubscriptionPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collSubscriptions);
				}
			} else {
				$count = count($this->collSubscriptions);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Subscription object to this object
	 * through the Subscription foreign key attribute.
	 *
	 * @param      Subscription $l Subscription
	 * @return     void
	 * @throws     PropelException
	 */
	public function addSubscription(Subscription $l)
	{
		if ($this->collSubscriptions === null) {
			$this->initSubscriptions();
		}
		if (!in_array($l, $this->collSubscriptions, true)) { // only add it if the **same** object is not already associated
			array_push($this->collSubscriptions, $l);
			$l->setUsergroup($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Usergroup is new, it will return
	 * an empty collection; or if this Usergroup has previously
	 * been saved, it will retrieve related Subscriptions from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Usergroup.
	 */
	public function getSubscriptionsJoinActivity($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSubscriptions === null) {
			if ($this->isNew()) {
				$this->collSubscriptions = array();
			} else {

				$criteria->add(SubscriptionPeer::USERGROUP_ID, $this->id);

				$this->collSubscriptions = SubscriptionPeer::doSelectJoinActivity($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SubscriptionPeer::USERGROUP_ID, $this->id);

			if (!isset($this->lastSubscriptionCriteria) || !$this->lastSubscriptionCriteria->equals($criteria)) {
				$this->collSubscriptions = SubscriptionPeer::doSelectJoinActivity($criteria, $con, $join_behavior);
			}
		}
		$this->lastSubscriptionCriteria = $criteria;

		return $this->collSubscriptions;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Usergroup is new, it will return
	 * an empty collection; or if this Usergroup has previously
	 * been saved, it will retrieve related Subscriptions from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Usergroup.
	 */
	public function getSubscriptionsJoinZone($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSubscriptions === null) {
			if ($this->isNew()) {
				$this->collSubscriptions = array();
			} else {

				$criteria->add(SubscriptionPeer::USERGROUP_ID, $this->id);

				$this->collSubscriptions = SubscriptionPeer::doSelectJoinZone($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SubscriptionPeer::USERGROUP_ID, $this->id);

			if (!isset($this->lastSubscriptionCriteria) || !$this->lastSubscriptionCriteria->equals($criteria)) {
				$this->collSubscriptions = SubscriptionPeer::doSelectJoinZone($criteria, $con, $join_behavior);
			}
		}
		$this->lastSubscriptionCriteria = $criteria;

		return $this->collSubscriptions;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Usergroup is new, it will return
	 * an empty collection; or if this Usergroup has previously
	 * been saved, it will retrieve related Subscriptions from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Usergroup.
	 */
	public function getSubscriptionsJoinCard($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSubscriptions === null) {
			if ($this->isNew()) {
				$this->collSubscriptions = array();
			} else {

				$criteria->add(SubscriptionPeer::USERGROUP_ID, $this->id);

				$this->collSubscriptions = SubscriptionPeer::doSelectJoinCard($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SubscriptionPeer::USERGROUP_ID, $this->id);

			if (!isset($this->lastSubscriptionCriteria) || !$this->lastSubscriptionCriteria->equals($criteria)) {
				$this->collSubscriptions = SubscriptionPeer::doSelectJoinCard($criteria, $con, $join_behavior);
			}
		}
		$this->lastSubscriptionCriteria = $criteria;

		return $this->collSubscriptions;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Usergroup is new, it will return
	 * an empty collection; or if this Usergroup has previously
	 * been saved, it will retrieve related Subscriptions from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Usergroup.
	 */
	public function getSubscriptionsJoinUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSubscriptions === null) {
			if ($this->isNew()) {
				$this->collSubscriptions = array();
			} else {

				$criteria->add(SubscriptionPeer::USERGROUP_ID, $this->id);

				$this->collSubscriptions = SubscriptionPeer::doSelectJoinUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SubscriptionPeer::USERGROUP_ID, $this->id);

			if (!isset($this->lastSubscriptionCriteria) || !$this->lastSubscriptionCriteria->equals($criteria)) {
				$this->collSubscriptions = SubscriptionPeer::doSelectJoinUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastSubscriptionCriteria = $criteria;

		return $this->collSubscriptions;
	}

	/**
	 * Clears out the collUsergroupHasActivitys collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addUsergroupHasActivitys()
	 */
	public function clearUsergroupHasActivitys()
	{
		$this->collUsergroupHasActivitys = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collUsergroupHasActivitys collection (array).
	 *
	 * By default this just sets the collUsergroupHasActivitys collection to an empty array (like clearcollUsergroupHasActivitys());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initUsergroupHasActivitys()
	{
		$this->collUsergroupHasActivitys = array();
	}

	/**
	 * Gets an array of UsergroupHasActivity objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Usergroup has previously been saved, it will retrieve
	 * related UsergroupHasActivitys from storage. If this Usergroup is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array UsergroupHasActivity[]
	 * @throws     PropelException
	 */
	public function getUsergroupHasActivitys($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUsergroupHasActivitys === null) {
			if ($this->isNew()) {
			   $this->collUsergroupHasActivitys = array();
			} else {

				$criteria->add(UsergroupHasActivityPeer::USERGROUP_ID, $this->id);

				UsergroupHasActivityPeer::addSelectColumns($criteria);
				$this->collUsergroupHasActivitys = UsergroupHasActivityPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(UsergroupHasActivityPeer::USERGROUP_ID, $this->id);

				UsergroupHasActivityPeer::addSelectColumns($criteria);
				if (!isset($this->lastUsergroupHasActivityCriteria) || !$this->lastUsergroupHasActivityCriteria->equals($criteria)) {
					$this->collUsergroupHasActivitys = UsergroupHasActivityPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastUsergroupHasActivityCriteria = $criteria;
		return $this->collUsergroupHasActivitys;
	}

	/**
	 * Returns the number of related UsergroupHasActivity objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related UsergroupHasActivity objects.
	 * @throws     PropelException
	 */
	public function countUsergroupHasActivitys(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collUsergroupHasActivitys === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(UsergroupHasActivityPeer::USERGROUP_ID, $this->id);

				$count = UsergroupHasActivityPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(UsergroupHasActivityPeer::USERGROUP_ID, $this->id);

				if (!isset($this->lastUsergroupHasActivityCriteria) || !$this->lastUsergroupHasActivityCriteria->equals($criteria)) {
					$count = UsergroupHasActivityPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collUsergroupHasActivitys);
				}
			} else {
				$count = count($this->collUsergroupHasActivitys);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a UsergroupHasActivity object to this object
	 * through the UsergroupHasActivity foreign key attribute.
	 *
	 * @param      UsergroupHasActivity $l UsergroupHasActivity
	 * @return     void
	 * @throws     PropelException
	 */
	public function addUsergroupHasActivity(UsergroupHasActivity $l)
	{
		if ($this->collUsergroupHasActivitys === null) {
			$this->initUsergroupHasActivitys();
		}
		if (!in_array($l, $this->collUsergroupHasActivitys, true)) { // only add it if the **same** object is not already associated
			array_push($this->collUsergroupHasActivitys, $l);
			$l->setUsergroup($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Usergroup is new, it will return
	 * an empty collection; or if this Usergroup has previously
	 * been saved, it will retrieve related UsergroupHasActivitys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Usergroup.
	 */
	public function getUsergroupHasActivitysJoinActivity($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUsergroupHasActivitys === null) {
			if ($this->isNew()) {
				$this->collUsergroupHasActivitys = array();
			} else {

				$criteria->add(UsergroupHasActivityPeer::USERGROUP_ID, $this->id);

				$this->collUsergroupHasActivitys = UsergroupHasActivityPeer::doSelectJoinActivity($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(UsergroupHasActivityPeer::USERGROUP_ID, $this->id);

			if (!isset($this->lastUsergroupHasActivityCriteria) || !$this->lastUsergroupHasActivityCriteria->equals($criteria)) {
				$this->collUsergroupHasActivitys = UsergroupHasActivityPeer::doSelectJoinActivity($criteria, $con, $join_behavior);
			}
		}
		$this->lastUsergroupHasActivityCriteria = $criteria;

		return $this->collUsergroupHasActivitys;
	}

	/**
	 * Clears out the collUsergroupHasChiefs collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addUsergroupHasChiefs()
	 */
	public function clearUsergroupHasChiefs()
	{
		$this->collUsergroupHasChiefs = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collUsergroupHasChiefs collection (array).
	 *
	 * By default this just sets the collUsergroupHasChiefs collection to an empty array (like clearcollUsergroupHasChiefs());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initUsergroupHasChiefs()
	{
		$this->collUsergroupHasChiefs = array();
	}

	/**
	 * Gets an array of UsergroupHasChief objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Usergroup has previously been saved, it will retrieve
	 * related UsergroupHasChiefs from storage. If this Usergroup is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array UsergroupHasChief[]
	 * @throws     PropelException
	 */
	public function getUsergroupHasChiefs($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUsergroupHasChiefs === null) {
			if ($this->isNew()) {
			   $this->collUsergroupHasChiefs = array();
			} else {

				$criteria->add(UsergroupHasChiefPeer::USERGROUP_ID, $this->id);

				UsergroupHasChiefPeer::addSelectColumns($criteria);
				$this->collUsergroupHasChiefs = UsergroupHasChiefPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(UsergroupHasChiefPeer::USERGROUP_ID, $this->id);

				UsergroupHasChiefPeer::addSelectColumns($criteria);
				if (!isset($this->lastUsergroupHasChiefCriteria) || !$this->lastUsergroupHasChiefCriteria->equals($criteria)) {
					$this->collUsergroupHasChiefs = UsergroupHasChiefPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastUsergroupHasChiefCriteria = $criteria;
		return $this->collUsergroupHasChiefs;
	}

	/**
	 * Returns the number of related UsergroupHasChief objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related UsergroupHasChief objects.
	 * @throws     PropelException
	 */
	public function countUsergroupHasChiefs(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collUsergroupHasChiefs === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(UsergroupHasChiefPeer::USERGROUP_ID, $this->id);

				$count = UsergroupHasChiefPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(UsergroupHasChiefPeer::USERGROUP_ID, $this->id);

				if (!isset($this->lastUsergroupHasChiefCriteria) || !$this->lastUsergroupHasChiefCriteria->equals($criteria)) {
					$count = UsergroupHasChiefPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collUsergroupHasChiefs);
				}
			} else {
				$count = count($this->collUsergroupHasChiefs);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a UsergroupHasChief object to this object
	 * through the UsergroupHasChief foreign key attribute.
	 *
	 * @param      UsergroupHasChief $l UsergroupHasChief
	 * @return     void
	 * @throws     PropelException
	 */
	public function addUsergroupHasChief(UsergroupHasChief $l)
	{
		if ($this->collUsergroupHasChiefs === null) {
			$this->initUsergroupHasChiefs();
		}
		if (!in_array($l, $this->collUsergroupHasChiefs, true)) { // only add it if the **same** object is not already associated
			array_push($this->collUsergroupHasChiefs, $l);
			$l->setUsergroup($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Usergroup is new, it will return
	 * an empty collection; or if this Usergroup has previously
	 * been saved, it will retrieve related UsergroupHasChiefs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Usergroup.
	 */
	public function getUsergroupHasChiefsJoinUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUsergroupHasChiefs === null) {
			if ($this->isNew()) {
				$this->collUsergroupHasChiefs = array();
			} else {

				$criteria->add(UsergroupHasChiefPeer::USERGROUP_ID, $this->id);

				$this->collUsergroupHasChiefs = UsergroupHasChiefPeer::doSelectJoinUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(UsergroupHasChiefPeer::USERGROUP_ID, $this->id);

			if (!isset($this->lastUsergroupHasChiefCriteria) || !$this->lastUsergroupHasChiefCriteria->equals($criteria)) {
				$this->collUsergroupHasChiefs = UsergroupHasChiefPeer::doSelectJoinUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastUsergroupHasChiefCriteria = $criteria;

		return $this->collUsergroupHasChiefs;
	}

	/**
	 * Clears out the collUsergroupHasUsers collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addUsergroupHasUsers()
	 */
	public function clearUsergroupHasUsers()
	{
		$this->collUsergroupHasUsers = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collUsergroupHasUsers collection (array).
	 *
	 * By default this just sets the collUsergroupHasUsers collection to an empty array (like clearcollUsergroupHasUsers());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initUsergroupHasUsers()
	{
		$this->collUsergroupHasUsers = array();
	}

	/**
	 * Gets an array of UsergroupHasUser objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Usergroup has previously been saved, it will retrieve
	 * related UsergroupHasUsers from storage. If this Usergroup is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array UsergroupHasUser[]
	 * @throws     PropelException
	 */
	public function getUsergroupHasUsers($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUsergroupHasUsers === null) {
			if ($this->isNew()) {
			   $this->collUsergroupHasUsers = array();
			} else {

				$criteria->add(UsergroupHasUserPeer::USERGROUP_ID, $this->id);

				UsergroupHasUserPeer::addSelectColumns($criteria);
				$this->collUsergroupHasUsers = UsergroupHasUserPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(UsergroupHasUserPeer::USERGROUP_ID, $this->id);

				UsergroupHasUserPeer::addSelectColumns($criteria);
				if (!isset($this->lastUsergroupHasUserCriteria) || !$this->lastUsergroupHasUserCriteria->equals($criteria)) {
					$this->collUsergroupHasUsers = UsergroupHasUserPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastUsergroupHasUserCriteria = $criteria;
		return $this->collUsergroupHasUsers;
	}

	/**
	 * Returns the number of related UsergroupHasUser objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related UsergroupHasUser objects.
	 * @throws     PropelException
	 */
	public function countUsergroupHasUsers(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collUsergroupHasUsers === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(UsergroupHasUserPeer::USERGROUP_ID, $this->id);

				$count = UsergroupHasUserPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(UsergroupHasUserPeer::USERGROUP_ID, $this->id);

				if (!isset($this->lastUsergroupHasUserCriteria) || !$this->lastUsergroupHasUserCriteria->equals($criteria)) {
					$count = UsergroupHasUserPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collUsergroupHasUsers);
				}
			} else {
				$count = count($this->collUsergroupHasUsers);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a UsergroupHasUser object to this object
	 * through the UsergroupHasUser foreign key attribute.
	 *
	 * @param      UsergroupHasUser $l UsergroupHasUser
	 * @return     void
	 * @throws     PropelException
	 */
	public function addUsergroupHasUser(UsergroupHasUser $l)
	{
		if ($this->collUsergroupHasUsers === null) {
			$this->initUsergroupHasUsers();
		}
		if (!in_array($l, $this->collUsergroupHasUsers, true)) { // only add it if the **same** object is not already associated
			array_push($this->collUsergroupHasUsers, $l);
			$l->setUsergroup($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Usergroup is new, it will return
	 * an empty collection; or if this Usergroup has previously
	 * been saved, it will retrieve related UsergroupHasUsers from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Usergroup.
	 */
	public function getUsergroupHasUsersJoinUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsergroupPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUsergroupHasUsers === null) {
			if ($this->isNew()) {
				$this->collUsergroupHasUsers = array();
			} else {

				$criteria->add(UsergroupHasUserPeer::USERGROUP_ID, $this->id);

				$this->collUsergroupHasUsers = UsergroupHasUserPeer::doSelectJoinUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(UsergroupHasUserPeer::USERGROUP_ID, $this->id);

			if (!isset($this->lastUsergroupHasUserCriteria) || !$this->lastUsergroupHasUserCriteria->equals($criteria)) {
				$this->collUsergroupHasUsers = UsergroupHasUserPeer::doSelectJoinUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastUsergroupHasUserCriteria = $criteria;

		return $this->collUsergroupHasUsers;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collReservations) {
				foreach ((array) $this->collReservations as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collSubscriptions) {
				foreach ((array) $this->collSubscriptions as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collUsergroupHasActivitys) {
				foreach ((array) $this->collUsergroupHasActivitys as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collUsergroupHasChiefs) {
				foreach ((array) $this->collUsergroupHasChiefs as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collUsergroupHasUsers) {
				foreach ((array) $this->collUsergroupHasUsers as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collReservations = null;
		$this->collSubscriptions = null;
		$this->collUsergroupHasActivitys = null;
		$this->collUsergroupHasChiefs = null;
		$this->collUsergroupHasUsers = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseUsergroup:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseUsergroup::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseUsergroup
